from enum import IntFlag, auto


class House(IntFlag):
    BROBNAR = auto()
    DIS = auto()
    LOGOS = auto()
    MARS = auto()
    SANCTUM = auto()
    SHADOWS = auto()
    UNTAMED = auto()
    BDL = BROBNAR | DIS | LOGOS
    BDM = BROBNAR | DIS | MARS
    BDS = BROBNAR | DIS | SANCTUM
    BDT = BROBNAR | DIS | SHADOWS
    BDU = BROBNAR | DIS | UNTAMED
    BLM = BROBNAR | LOGOS | MARS
    BLS = BROBNAR | LOGOS | SANCTUM
    BLT = BROBNAR | LOGOS | SHADOWS
    BLU = BROBNAR | LOGOS | UNTAMED
    BMS = BROBNAR | MARS | SANCTUM
    BMT = BROBNAR | MARS | SHADOWS
    BMU = BROBNAR | MARS | UNTAMED
    BST = BROBNAR | SANCTUM | SHADOWS
    BSU = BROBNAR | SANCTUM | UNTAMED
    BTU = BROBNAR | SHADOWS | UNTAMED
    DLM = DIS | LOGOS | MARS
    DLS = DIS | LOGOS | SANCTUM
    DLT = DIS | LOGOS | SHADOWS
    DLU = DIS | LOGOS | UNTAMED
    DMS = DIS | MARS | SANCTUM
    DMT = DIS | MARS | SHADOWS
    DMU = DIS | MARS | UNTAMED
    DST = DIS | SANCTUM | SHADOWS
    DSU = DIS | SANCTUM | UNTAMED
    DTU = DIS | SHADOWS | UNTAMED
    LMS = LOGOS | MARS | SANCTUM
    LMT = LOGOS | MARS | SHADOWS
    LMU = LOGOS | MARS | UNTAMED
    LST = LOGOS | SANCTUM | SHADOWS
    LSU = LOGOS | SANCTUM | UNTAMED
    LTU = LOGOS | SHADOWS | UNTAMED
    MST = MARS | SANCTUM | SHADOWS
    MSU = MARS | SANCTUM | UNTAMED
    MTU = MARS | SHADOWS | UNTAMED
    STU = SANCTUM | SHADOWS | UNTAMED
